In [1]:
import pandas as pd

In [2]:
df_screen = pd.read_csv("npass_predict_file.csv")

In [3]:
df_screen

,Compound_Name,mol,prediction
0,NPC124005,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cc(C/C=C(\C)/C...,6.201828
1,NPC129042,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c(C/C=C(\C)/C)cc...,6.249459
2,NPC184476,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2c(C/C=C(\C)/C)...,6.264795
3,NPC242556,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cccc3)/C(O)NC1=C,5.716387
4,NPC100002,BrCBr,5.106366
...,...,...,...
30865,NPC99909,O=C1C(C)(C)[C@]2[C@@](C)(C3=C(C(=O)C2)[C@@]2(C...,5.674556
30866,NPC99937,Clc1c(C)c(C(=O)O[C@]2C3=C(C=O)[C@@](O)[C@]4[C@...,6.046190
30867,NPC99939,O=C1C(c2c3c([nH]c2)cccc3)=N[C@](c2c3c([nH]c2)c...,5.329131
30868,NPC99957,O(C)c1c(O)c2C(=O)C=C(C)Oc2cc1O[C@]1[C@](O)[C@@...,6.605725
30869,NPC99968,O(C)c1c2oc(-c3cc4OCOc4cc3)cc2cc(CCCO)c1,6.010638

In [4]:
top_comps = df_screen.sort_values(by='prediction', ascending=False)

In [5]:
top_comps

,Compound_Name,mol,prediction
22902,NPC473618,O(C)c1c2Oc3c(c(O)c(c(O)c3)-c3c(O)c4C(=O)c5c(O)...,7.599104
6468,NPC185275,O(C)c1cc(O)c2C(=O)c3c(O)c(-c4c(O)c(c(O)c5C(=O)...,7.595199
23142,NPC473895,O(C)c1c(OC)c2C(=O)C(c3ccc(OC)cc3)=COc2cc1O[C@]...,7.588675
2462,NPC132111,O=C1C(c2c(O[C@]3[C@](O)[C@@](O)[C@](O)[C@@](CO...,7.522182
17434,NPC324742,O(C)c1cc(O)c2C(=O)c3c(O)c(-c4c(O)c(c(O)c5C(=O)...,7.508647
...,...,...,...
16172,NPC312003,O=C(OC(OC(=O)C)C)C,4.294524
17640,NPC327070,O=C(OCC(O)(COC(=O)C)c1c(O)cc(C)cc1)/C(=C/C)/C,4.209523
17467,NPC325102,O=C(OC(C(COC(=O)C(C)C)(C)C)C(C)C)C(C)C,4.176129
4562,NPC160235,O=C(OCC(O)(COC(=O)C(C)C)c1c(O)cc(C)cc1)C(C)C,4.095673
13900,NPC281883,O=C(OC(COC(=O)C)COC(=O)C)C,3.975251

In [6]:
top_comps.iloc[:25, ].to_csv("top_25_comps_of_npass.csv")