In [1]:
import pandas as pd

In [2]:
df_1 = pd.read_csv("Substructure_final_dataset_for_model.csv")

In [3]:
df_1

,pIC50,SubFPC1,SubFPC2,SubFPC3,SubFPC5,SubFPC9,SubFPC13,SubFPC18,SubFPC49,SubFPC84,...,SubFPC179,SubFPC180,SubFPC183,SubFPC275,SubFPC279,SubFPC287,SubFPC295,SubFPC302,SubFPC303,SubFPC307
0,7.301030,0,3,0,1,0,0,0,0,1,...,0,0,0,0,0,2,8,5,2,18
1,6.075721,0,3,0,1,6,0,0,0,1,...,0,0,0,0,0,2,7,7,2,19
2,7.698970,0,3,0,1,3,0,0,0,1,...,0,0,0,0,0,2,7,6,2,18
3,5.244125,0,3,0,1,3,0,0,0,1,...,0,0,0,0,0,2,7,6,2,18
4,5.075721,0,3,0,1,0,0,1,0,1,...,0,0,0,0,0,2,7,5,2,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967,6.872895,0,3,0,1,0,0,1,0,1,...,0,0,0,0,0,2,7,5,2,17
968,8.096910,0,3,0,1,0,0,1,0,1,...,0,0,0,0,0,2,7,5,2,17
969,8.154902,0,3,0,1,3,0,0,0,1,...,0,0,0,0,0,2,7,6,2,18
970,7.481486,0,3,0,1,3,0,0,0,1,...,0,0,0,0,0,2,7,6,2,18
971,6.387216,0,3,0,1,0,0,0,0,1,...,0,0,0,0,0,2,5,4,2,17

In [4]:
df_1.drop(columns="pIC50", inplace=True)

In [5]:
df_unknown_1 = pd.read_csv("npass_SubstructureCount.csv")

In [6]:
df_unknown_1

,Name,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,SubFPC8,SubFPC9,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,NPC124005,5.0,1.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,17.0,17.0,5.0,0.0,0.0,0.0,0.0,18.0
1,NPC129042,7.0,2.0,0.0,1.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,21.0,21.0,7.0,0.0,0.0,0.0,0.0,20.0
2,NPC184476,6.0,2.0,0.0,1.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,21.0,21.0,7.0,0.0,0.0,0.0,0.0,21.0
3,NPC242556,3.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,13.0,13.0,3.0,0.0,0.0,0.0,0.0,16.0
4,NPC100002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30921,NPC99909,8.0,9.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,29.0,29.0,5.0,1.0,0.0,0.0,0.0,13.0
30922,NPC99937,4.0,3.0,2.0,2.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,20.0,20.0,5.0,1.0,0.0,0.0,0.0,16.0
30923,NPC99939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9.0,9.0,2.0,0.0,0.0,0.0,0.0,22.0
30924,NPC99957,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,27.0,27.0,6.0,1.0,0.0,0.0,0.0,19.0
30925,NPC99968,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,7.0,4.0,0.0,0.0,0.0,0.0,14.0

In [7]:
col_names = df_1.columns.to_list()

In [8]:
print(col_names)

['SubFPC1', 'SubFPC2', 'SubFPC3', 'SubFPC5', 'SubFPC9', 'SubFPC13', 'SubFPC18', 'SubFPC49', 'SubFPC84', 'SubFPC85', 'SubFPC88', 'SubFPC100', 'SubFPC133', 'SubFPC135', 'SubFPC136', 'SubFPC137', 'SubFPC171', 'SubFPC172', 'SubFPC179', 'SubFPC180', 'SubFPC183', 'SubFPC275', 'SubFPC279', 'SubFPC287', 'SubFPC295', 'SubFPC302', 'SubFPC303', 'SubFPC307']

In [9]:
df_unknown_1_ = df_unknown_1.loc[:, col_names]

In [10]:
df_unknown_1_

,SubFPC1,SubFPC2,SubFPC3,SubFPC5,SubFPC9,SubFPC13,SubFPC18,SubFPC49,SubFPC84,SubFPC85,...,SubFPC179,SubFPC180,SubFPC183,SubFPC275,SubFPC279,SubFPC287,SubFPC295,SubFPC302,SubFPC303,SubFPC307
0,5.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,5.0,0.0,18.0
1,7.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,7.0,0.0,20.0
2,6.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,7.0,0.0,21.0
3,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,3.0,0.0,16.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30921,8.0,9.0,3.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,1.0,13.0
30922,4.0,3.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,5.0,1.0,16.0
30923,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,4.0,0.0,3.0,9.0,2.0,0.0,22.0
30924,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,3.0,20.0,6.0,1.0,19.0
30925,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,9.0,4.0,0.0,14.0

In [11]:
df_unknown_1_names_mol = pd.read_csv("npass_database.csv")

In [12]:
df_unknown_1_names_mol

       comp_name                                                mol
0      NPC124005  OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cc(C/C=C(\C)/C...
1      NPC129042  OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c(C/C=C(\C)/C)cc...
2      NPC184476  OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2c(C/C=C(\C)/C)...
3      NPC242556   OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cccc3)/C(O)NC1=C
4      NPC100002                                              BrCBr
...          ...                                                ...
30921   NPC99909  O=C1C(C)(C)[C@]2[C@@](C)(C3=C(C(=O)C2)[C@@]2(C...
30922   NPC99937  Clc1c(C)c(C(=O)O[C@]2C3=C(C=O)[C@@](O)[C@]4[C@...
30923   NPC99939  O=C1C(c2c3c([nH]c2)cccc3)=N[C@](c2c3c([nH]c2)c...
30924   NPC99957  O(C)c1c(O)c2C(=O)C=C(C)Oc2cc1O[C@]1[C@](O)[C@@...
30925   NPC99968            O(C)c1c2oc(-c3cc4OCOc4cc3)cc2cc(CCCO)c1

[30926 rows x 2 columns]

In [13]:
df_unknown_1_merge = pd.concat([df_unknown_1_names_mol, df_unknown_1_], axis=1)

In [14]:
df_unknown_1_merge

,comp_name,mol,SubFPC1,SubFPC2,SubFPC3,SubFPC5,SubFPC9,SubFPC13,SubFPC18,SubFPC49,...,SubFPC179,SubFPC180,SubFPC183,SubFPC275,SubFPC279,SubFPC287,SubFPC295,SubFPC302,SubFPC303,SubFPC307
0,NPC124005,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cc(C/C=C(\C)/C...,5.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,5.0,0.0,18.0
1,NPC129042,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c(C/C=C(\C)/C)cc...,7.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,7.0,0.0,20.0
2,NPC184476,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2c(C/C=C(\C)/C)...,6.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,7.0,0.0,21.0
3,NPC242556,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cccc3)/C(O)NC1=C,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,3.0,0.0,16.0
4,NPC100002,BrCBr,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30921,NPC99909,O=C1C(C)(C)[C@]2[C@@](C)(C3=C(C(=O)C2)[C@@]2(C...,8.0,9.0,3.0,1.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,1.0,13.0
30922,NPC99937,Clc1c(C)c(C(=O)O[C@]2C3=C(C=O)[C@@](O)[C@]4[C@...,4.0,3.0,2.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,5.0,1.0,16.0
30923,NPC99939,O=C1C(c2c3c([nH]c2)cccc3)=N[C@](c2c3c([nH]c2)c...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,4.0,0.0,3.0,9.0,2.0,0.0,22.0
30924,NPC99957,O(C)c1c(O)c2C(=O)C=C(C)Oc2cc1O[C@]1[C@](O)[C@@...,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,3.0,0.0,3.0,20.0,6.0,1.0,19.0
30925,NPC99968,O(C)c1c2oc(-c3cc4OCOc4cc3)cc2cc(CCCO)c1,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,9.0,4.0,0.0,14.0

In [15]:
df_unknown_1_merge_na = df_unknown_1_merge.dropna()

In [16]:
df_unknown_1_merge_na.reset_index(inplace=True)

In [17]:
df_unknown_1_merge_na

,index,comp_name,mol,SubFPC1,SubFPC2,SubFPC3,SubFPC5,SubFPC9,SubFPC13,SubFPC18,...,SubFPC179,SubFPC180,SubFPC183,SubFPC275,SubFPC279,SubFPC287,SubFPC295,SubFPC302,SubFPC303,SubFPC307
0,0,NPC124005,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cc(C/C=C(\C)/C...,5.0,1.0,0.0,3.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,5.0,0.0,18.0
1,1,NPC129042,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c(C/C=C(\C)/C)cc...,7.0,2.0,0.0,4.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,7.0,0.0,20.0
2,2,NPC184476,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2c(C/C=C(\C)/C)...,6.0,2.0,0.0,4.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,7.0,0.0,21.0
3,3,NPC242556,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cccc3)/C(O)NC1=C,3.0,0.0,0.0,2.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,3.0,0.0,16.0
4,4,NPC100002,BrCBr,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30865,30921,NPC99909,O=C1C(C)(C)[C@]2[C@@](C)(C3=C(C(=O)C2)[C@@]2(C...,8.0,9.0,3.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,1.0,13.0
30866,30922,NPC99937,Clc1c(C)c(C(=O)O[C@]2C3=C(C=O)[C@@](O)[C@]4[C@...,4.0,3.0,2.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,5.0,1.0,16.0
30867,30923,NPC99939,O=C1C(c2c3c([nH]c2)cccc3)=N[C@](c2c3c([nH]c2)c...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,4.0,0.0,3.0,9.0,2.0,0.0,22.0
30868,30924,NPC99957,O(C)c1c(O)c2C(=O)C=C(C)Oc2cc1O[C@]1[C@](O)[C@@...,2.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,3.0,0.0,3.0,20.0,6.0,1.0,19.0
30869,30925,NPC99968,O(C)c1c2oc(-c3cc4OCOc4cc3)cc2cc(CCCO)c1,0.0,2.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,3.0,0.0,0.0,9.0,4.0,0.0,14.0

In [18]:
df_unknown_1_merge_na.drop(columns="index", inplace=True)

C:\Users\CADD\AppData\Local\Temp\ipykernel_1888\1436220650.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unknown_1_merge_na.drop(columns="index", inplace=True)

In [19]:
df_unknown_1_merge_na

,comp_name,mol,SubFPC1,SubFPC2,SubFPC3,SubFPC5,SubFPC9,SubFPC13,SubFPC18,SubFPC49,...,SubFPC179,SubFPC180,SubFPC183,SubFPC275,SubFPC279,SubFPC287,SubFPC295,SubFPC302,SubFPC303,SubFPC307
0,NPC124005,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cc(C/C=C(\C)/C...,5.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,5.0,0.0,18.0
1,NPC129042,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c(C/C=C(\C)/C)cc...,7.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,7.0,0.0,20.0
2,NPC184476,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2c(C/C=C(\C)/C)...,6.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,7.0,0.0,21.0
3,NPC242556,OC1/C(=C/c2c(C(C=C)(C)C)[nH]c3c2cccc3)/C(O)NC1=C,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,0.0,2.0,6.0,3.0,0.0,16.0
4,NPC100002,BrCBr,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30865,NPC99909,O=C1C(C)(C)[C@]2[C@@](C)(C3=C(C(=O)C2)[C@@]2(C...,8.0,9.0,3.0,1.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,1.0,13.0
30866,NPC99937,Clc1c(C)c(C(=O)O[C@]2C3=C(C=O)[C@@](O)[C@]4[C@...,4.0,3.0,2.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,5.0,1.0,16.0
30867,NPC99939,O=C1C(c2c3c([nH]c2)cccc3)=N[C@](c2c3c([nH]c2)c...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,4.0,0.0,3.0,9.0,2.0,0.0,22.0
30868,NPC99957,O(C)c1c(O)c2C(=O)C=C(C)Oc2cc1O[C@]1[C@](O)[C@@...,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,3.0,0.0,3.0,20.0,6.0,1.0,19.0
30869,NPC99968,O(C)c1c2oc(-c3cc4OCOc4cc3)cc2cc(CCCO)c1,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,9.0,4.0,0.0,14.0

In [20]:
df_unknown_1_merge_na.iloc[:, :].to_csv("unseen_npass_opt_data.csv", index=False)