# **Calculating molecular fingerprints using padelpy**

# **Install padelpy**

In [1]:
# ! pip install padelpy

# **Prepare fingerprint XML**

In [2]:
# ! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
# ! unzip fingerprints_xml.zip

### **List and sort fingerprint XML files**

In [3]:
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files

['AtomPairs2DFingerprintCount.xml',
 'AtomPairs2DFingerprinter.xml',
 'EStateFingerprinter.xml',
 'ExtendedFingerprinter.xml',
 'Fingerprinter.xml',
 'GraphOnlyFingerprinter.xml',
 'KlekotaRothFingerprintCount.xml',
 'KlekotaRothFingerprinter.xml',
 'MACCSFingerprinter.xml',
 'PubchemFingerprinter.xml',
 'SubstructureFingerprintCount.xml',
 'SubstructureFingerprinter.xml']

In [4]:
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

### **Create a dictionary**

In [5]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

# **Load FASII dataset**

In [6]:
import pandas as pd

df = pd.read_csv('DHODH_final_dataset_pIC50.csv')
df.head()

,chembl_id,smiles,bioactivity,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,CHEMBL154151,CN(C)c1ccc(-c2ccc(NC(=O)C3=C(C(=O)O)CCC3)cc2Cl...,active,384.863,4.5766,2.0,3.0,7.301030
1,CHEMBL157004,O=C(O)C1=C(C(=O)Nc2ccc(-c3cccc(OC(F)(F)F)c3)cc...,active,459.342,5.7746,2.0,3.0,6.075721
2,CHEMBL345464,O=C(O)C1=C(C(=O)Nc2ccc(-c3cccc(OC(F)(F)F)c3)c(...,active,425.790,5.4092,2.0,3.0,7.698970
3,CHEMBL154214,O=C(O)C1=C(C(=O)Nc2ccc(-c3ccc(OC(F)(F)F)cc3)cc...,intermediate,409.335,4.8949,2.0,3.0,5.244125
4,CHEMBL358435,COc1ccc(-c2ccc(NC(=O)C3=C(C(=O)O)CCC3)c(Cl)c2)cc1,intermediate,371.820,4.5192,2.0,3.0,5.075721

In [7]:
df.tail()

,chembl_id,smiles,bioactivity,MW,LogP,NumHDonors,NumHAcceptors,pIC50
982,CHEMBL197194,COc1cccc(-c2ccc(NC(=O)C3=C(C(=O)O)CCC3)c(F)c2)c1,active,355.365,4.0049,2.0,3.0,6.872895
983,CHEMBL345701,COc1ccccc1-c1c(F)c(F)c(NC(=O)C2=C(C(=O)O)CCC2)...,active,409.335,4.4222,2.0,3.0,8.096910
984,CHEMBL154623,O=C(O)C1=C(C(=O)Nc2c(F)c(F)c(-c3cccc(OC(F)(F)F...,active,463.305,5.3122,2.0,3.0,8.154902
985,CHEMBL157105,O=C(O)C1=C(C(=O)Nc2c(F)cc(-c3cccc(OC(F)(F)F)c3...,active,427.325,5.0340,2.0,3.0,7.481486
986,CHEMBL348270,O=C(O)C1=C(C(=O)Nc2ccc(-c3ccccc3)cc2)CCC1,active,307.349,3.8572,2.0,2.0,6.387216

# **Prepare data subset as input to PaDEL**

In [8]:
df2 = pd.concat([df['smiles'],df['chembl_id']], axis=1)
df2.to_csv('molecule.smi', sep='\t', index=False, header=False)
df2

                                                smiles     chembl_id
0    CN(C)c1ccc(-c2ccc(NC(=O)C3=C(C(=O)O)CCC3)cc2Cl...  CHEMBL154151
1    O=C(O)C1=C(C(=O)Nc2ccc(-c3cccc(OC(F)(F)F)c3)cc...  CHEMBL157004
2    O=C(O)C1=C(C(=O)Nc2ccc(-c3cccc(OC(F)(F)F)c3)c(...  CHEMBL345464
3    O=C(O)C1=C(C(=O)Nc2ccc(-c3ccc(OC(F)(F)F)cc3)cc...  CHEMBL154214
4    COc1ccc(-c2ccc(NC(=O)C3=C(C(=O)O)CCC3)c(Cl)c2)cc1  CHEMBL358435
..                                                 ...           ...
982   COc1cccc(-c2ccc(NC(=O)C3=C(C(=O)O)CCC3)c(F)c2)c1  CHEMBL197194
983  COc1ccccc1-c1c(F)c(F)c(NC(=O)C2=C(C(=O)O)CCC2)...  CHEMBL345701
984  O=C(O)C1=C(C(=O)Nc2c(F)c(F)c(-c3cccc(OC(F)(F)F...  CHEMBL154623
985  O=C(O)C1=C(C(=O)Nc2c(F)cc(-c3cccc(OC(F)(F)F)c3...  CHEMBL157105
986          O=C(O)C1=C(C(=O)Nc2ccc(-c3ccccc3)cc2)CCC1  CHEMBL348270

[987 rows x 2 columns]

# **Calculate descriptors**

There are 12 fingerprint types in PaDEL. To calculate all 12, make sure to make adjustments to the ***descriptortypes*** input argument to any of the ones in the ***fp*** dictionary variable as shown above, e.g. *SubstructureFingerprintCount.xml*

In [9]:
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [10]:
from padelpy import padeldescriptor

for i in fp:
        fingerprint = i
    
        fingerprint_output_file = ''.join([fingerprint,'.csv']) #Substructure.csv
        fingerprint_descriptortypes = fp[fingerprint]
    
        padeldescriptor(mol_dir='molecule.smi',
                        d_file=fingerprint_output_file, #'Substructure.csv'
                        #descriptortypes='SubstructureFingerprint.xml',
                        descriptortypes= fingerprint_descriptortypes,
                        detectaromaticity=True,
                        standardizenitro=True,
                        standardizetautomers=True,
                        threads=2,
                        removesalt=True,
                        log=True,
                        fingerprints=True)